peer_eval/config/routes.rb
Rails.application.routes.draw do
	get 'reviews/:id', to: 'peer_evaluations#index'
 	devise_for :students, path: 'u'
	resources :students
	resources :groups
	resources :projects
	resources :assignments
	resources :memberships
	resources :scores
	resources :reviews
	resources :peer_evaluations
  resources :grades

	root to: 'students#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

peer_eval/app/models/score.rb
class Score < ApplicationRecord
  belongs_to :author, class_name: 'Student'
  belongs_to :recipient, class_name: 'Student'
  belongs_to :review, optional: true

  validates :rating, presence: true
end

peer_eval/app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: %i[ show edit update destroy ]

  # GET /scores or /scores.json
  def index
    @scores = Score.all
    @students = Student.all
    @groups = Group.all
    @projects = Project.all
    unless current_student.try(:isAdmin?)
      render(:file => File.join(Rails.root, 'public/403'), :formats => [:html], :status => 403, :layout => false)
    end
  end

  # GET /scores/1 or /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores or /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        @scores = Project.all
        format.html { render action: "index", notice: "Score was successfully created." }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1 or /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: "Score was successfully updated." }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1 or /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: "Score was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def score_params
      params.require(:score).permit(:rating, :author_id, :recipient_id, :review_id)
    end
end

peer_eval/app/helpers/scores_helper.rb
module ScoresHelper
  def average_score(project, user)
    sum = 0.0
    count = 0.0
    scores = Score.where(recipient_id: user)
    puts scores.length
    scores.each do |score|
      if (Review.find_by(id: score.review_id).project_id == project)
        sum += score.rating
        count += 1
      end
    end
    return sum/count
  end

  def setup_grade(student, project)
    grade = Grade.find_by(student_id: student.id, project_id: project.id)
    if grade == nil
      Grade.new(params[:grade])
    else
      grade
    end
  end
end

peer_eval/app/views/scores/_form.html.erb
<%= form_with(model: score, local: true) do |form| %>
  <% if score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
        <% score.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.number_field :author_id %>
  </div>

  <div class="field">
    <%= form.label :recipient_id %>
    <%= form.number_field :recipient_id %>
  </div>

  <div class="field">
    <%= form.label :review_id %>
    <%= form.number_field :review_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

peer_eval/app/views/scores/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

peer_eval/app/views/scores/index.html.erb
<%= stylesheet_link_tag "scores" %>
<meta name="turbolinks-cache-control" content="no-cache">
<% flash.each do |type, msg| %>
  <div>
    <%if type =="errors"%>
      <b style="color:Red;"><%= msg %></b>
    <% else %>
      <b style="color:green;"><%= msg %></b>
    <% end %>
  </div>
<%end %>

<h1 class="title">Scores</h1>
<% @groups.each do |group| %>
  <button type="button" class="collapsible"><%= group.name %></button>
  <div class = "content">
    <% @projects.each do |project| %>
      <% if Assignment.exists?(group_id: group.id, project_id: project.id) %>
        <button type="button" class = "collapsible scarlet"><%= project.title %></button>
        <div class = "content">
          <%members = Membership.where(group_id: group.id) %>
          <%members.each do |member| %>
            <% student = Student.find_by(id: member.student_id)
               review = Review.find_by(student_id: student.id, project_id: project.id)%>
            <button type="button" class = "collapsible"><%="#{student.fname} #{student.lname}" %></button>
            <div class = "content">
            <% if(review != nil) %>
                  <p>Average rating by group: <%=average_score(project.id, student.id) %>
                  <% scores= Score.where(review_id: review.id) %>
                  <%scores.each do |score| %>
                  <br><%="#{Student.find_by(id: score.recipient_id).fname} #{Student.find_by(id: score.recipient_id).lname}: #{score.rating} " %>
                  <% end %>
                   <br> <%="Comment: #{review.comment}" %>
                  </p>
            <% else %>
                <p> Average rating by group: <%=average_score(project.id, student.id) %>
                  <br> No review submitted.</p>
            <%end %>
              <% grade = Grade.find_by(student_id: student.id, project_id: project.id)
                 display = "initial"%>
              <% if(grade != nil)
                   projectGrade = grade.projectGrade
                   else
                     projectGrade = ""
                 end %>
                <p><%= "Grade: #{projectGrade}" %> </p>
            <div>
              <%= form_for setup_grade(student, project) do |f| %>
                <%= f.text_field :projectGrade %>
                <%= f.hidden_field :project_id, value: project.id %>
                <%= f.hidden_field :student_id, value: student.id %>
                <%= f.submit %>
              <%end %>
            </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <%end %>
  </div>
<% end %>



<script>
document.addEventListener("turbolinks:load", function() {
    let coll = document.getElementsByClassName("collapsible");
    let i;

    for (i = 0; i < coll.length; i++) {
        coll[i].addEventListener("click", function () {
            this.classList.toggle("active");
            let content = this.nextElementSibling;
            if (content.className == "content") {
                if (content.style.display === "block") {
                    content.style.display = "none";
                } else {
                    content.style.display = "block";
                }
            }
        });
    }
})
</script>
<!--<p id="notice"><%#= notice %></p>-->

<!--<h1>Scores</h1>-->

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Rating</th>-->
<!--      <th>Author</th>-->
<!--      <th>Recipient</th>-->
<!--      <th>Review</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
    <%# @scores.each do |score| %>
<!--      <tr>-->
<!--        <td><%#= score.rating %></td>-->
<!--        <td><%#= score.author %></td>-->
<!--        <td><%#= score.recipient %></td>-->
<!--        <td><%#= score.review_id %></td>-->
<!--        <td><%#= link_to 'Show', score %></td>-->
<!--        <td><%#= link_to 'Edit', edit_score_path(score) %></td>-->
<!--        <td><%#= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
    <%# end %>
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->

<%#= link_to 'New Score', new_score_path %>

peer_eval/app/views/scores/new.html.erb
<h1>New Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Back', scores_path %>

peer_eval/app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @score.rating %>
</p>

<p>
  <strong>Author:</strong>
  <%= @score.author %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @score.recipient %>
</p>

<p>
  <strong>Review:</strong>
  <%= @score.review_id %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>