peer_eval/config/routes.rb
Rails.application.routes.draw do
	get 'reviews/:id', to: 'peer_evaluations#index'
 	devise_for :students, path: 'u'
	resources :students
	resources :groups
	resources :projects
	resources :assignments
	resources :memberships
	resources :scores
	resources :reviews
	resources :peer_evaluations
  resources :grades

	root to: 'students#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

peer_eval/app/models/admin.rb
class Admin < ApplicationRecord
end

peer_eval/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

peer_eval/app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :group
  belongs_to :project
end

peer_eval/app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :author, class_name: 'Student'
  belongs_to :recipient, class_name: 'Student'
end

peer_eval/app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :student
  belongs_to :project
  validates :projectGrade, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
end

peer_eval/app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :students, through: :memberships
  has_many :assignments, dependent: :destroy
  has_many :projects, through: :assignments
  has_many :reviews
  validates :name, presence: true, uniqueness: true
end

peer_eval/app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :student
  belongs_to :group
end

peer_eval/app/models/project.rb
class Project < ApplicationRecord
  has_many :assignments, dependent: :destroy
  has_many :groups, through: :assignments
  has_many :reviews
  has_many :grades

  validates :title, presence: true, uniqueness: true

  validates :due, presence: true
  validate :due_date_must_be_in_the_future

  def due_date_must_be_in_the_future
  	if due.present? && due < Date.today
      errors.add(:due, "must be in the future")
    end
  end
end

peer_eval/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :group
  belongs_to :project
  belongs_to :student

  has_many :scores, dependent: :delete_all
  accepts_nested_attributes_for :scores
end

peer_eval/app/models/score.rb
class Score < ApplicationRecord
  belongs_to :author, class_name: 'Student'
  belongs_to :recipient, class_name: 'Student'
  belongs_to :review, optional: true

  validates :rating, presence: true
end

peer_eval/app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :memberships, dependent: :destroy
  has_many :groups, through: :memberships
  has_many :authored_scores, class_name: "Score", foreign_key: "author_id"
  has_many :received_scores, class_name: "Score", foreign_key: "recipient_id"
  has_many :scores
  has_many :reviews
  has_many :grades
  validates :fname, :lname, :email, presence: true
  validates :groups, absence: { message: 'cannot have admins as members' }, if: :isAdmin?
  validates_uniqueness_of :email
end

peer_eval/app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: %i[ show edit update destroy ]

  # GET /grades or /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1 or /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades or /grades.json
  def create
    @grade = Grade.new(grade_params)
    if @grade.save
      flash[:success] = "Grade was successfully created"
      redirect_to grades_path
    else
      flash[:errors] = @grade.errors.full_messages.join(' ')
      redirect_to grades_path
    end
  end

  # PATCH/PUT /grades/1 or /grades/1.json
  def update
    if @grade.save
      flash[:success] = "Grade was successfully updated"
      redirect_to grades_path
    else
      flash[:errors] = @grade.errors.full_messages.join(' ')
      redirect_to grades_path
    end
  end

  # DELETE /grades/1 or /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: "Grade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grade_params
      params.require(:grade).permit(:project_id, :student_id, :projectGrade)
    end
end

peer_eval/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
    unless current_student.try(:isAdmin?)
      render(:file => File.join(Rails.root, 'public/403'), :formats => [:html], :status => 403, :layout => false)
    end
  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)
    if @review.save
      flash[:success] = "Review was successfully created"
      redirect_to peer_evaluations_path
      else
        flash[:errors] = @review.errors.full_messages.join(' ')
        redirect_to peer_evaluations_path
    end
    #
    # respond_to do |format|
    #   if @review.save
    #     format.html { redirect_to @review, notice: "Review was successfully created." }
    #     format.json { render :show, status: :created, location: @review }
    #   else
    #     flash[:error] = @review.errors.full_messages.join(' ')
    #     # format.html { render :new, status: :unprocessable_entity }
    #     # format.json { render json: @review.errors, status: :unprocessable_entity }
    #   end
    # end

  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:comment, :group_id, :project_id, :student_id, scores_attributes: [:id, :rating, :author_id, :recipient_id, :review_id])
    end
end

peer_eval/app/helpers/application_helper.rb
module ApplicationHelper
end

peer_eval/app/helpers/assignments_helper.rb
module AssignmentsHelper
end

peer_eval/app/helpers/grades_helper.rb
module GradesHelper
end

peer_eval/app/helpers/groups_helper.rb
module GroupsHelper
end

peer_eval/app/helpers/memberships_helper.rb
module MembershipsHelper
end

peer_eval/app/helpers/projects_helper.rb
module ProjectsHelper
end

peer_eval/app/helpers/reviews_helper.rb
module ReviewsHelper

end

peer_eval/app/helpers/scores_helper.rb
module ScoresHelper
  def average_score(project, user)
    sum = 0.0
    count = 0.0
    scores = Score.where(recipient_id: user)
    puts scores.length
    scores.each do |score|
      if (Review.find_by(id: score.review_id).project_id == project)
        sum += score.rating
        count += 1
      end
    end
    return sum/count
  end

  def setup_grade(student, project)
    grade = Grade.find_by(student_id: student.id, project_id: project.id)
    if grade == nil
      Grade.new(params[:grade])
    else
      grade
    end
  end
end

peer_eval/app/helpers/students_helper.rb
module StudentsHelper
end

peer_eval/app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.number_field :group_id %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.number_field :project_id %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.number_field :student_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

peer_eval/app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

peer_eval/app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Group</th>
      <th>Project</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.comment %></td>
        <td><%= review.group_id %></td>
        <td><%= review.project_id %></td>
        <td><%= review.student_id %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

peer_eval/app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', peer_evaluations_path %>

peer_eval/app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Group:</strong>
  <%= @review.group_id %>
</p>

<p>
  <strong>Project:</strong>
  <%= @review.project_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @review.student_id %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', peer_evaluations_path %>