peer_eval/config/routes.rb
Rails.application.routes.draw do
	get 'reviews/:id', to: 'peer_evaluations#index'
 	devise_for :students, path: 'u'
	resources :students
	resources :groups
	resources :projects
	resources :assignments
	resources :memberships
	resources :scores
	resources :reviews
	resources :peer_evaluations
  resources :grades

	root to: 'students#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

peer_eval/app/models/admin.rb
class Admin < ApplicationRecord
end

peer_eval/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

peer_eval/app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :group
  belongs_to :project
end

peer_eval/app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :author, class_name: 'Student'
  belongs_to :recipient, class_name: 'Student'
end

peer_eval/app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :student
  belongs_to :project
  validates :projectGrade, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
end

peer_eval/app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :students, through: :memberships
  has_many :assignments, dependent: :destroy
  has_many :projects, through: :assignments
  has_many :reviews
  validates :name, presence: true, uniqueness: true
end

peer_eval/app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :student
  belongs_to :group
end

peer_eval/app/models/project.rb
class Project < ApplicationRecord
  has_many :assignments, dependent: :destroy
  has_many :groups, through: :assignments
  has_many :reviews
  has_many :grades

  validates :title, presence: true, uniqueness: true

  validates :due, presence: true
  validate :due_date_must_be_in_the_future

  def due_date_must_be_in_the_future
  	if due.present? && due < Date.today
      errors.add(:due, "must be in the future")
    end
  end
end

peer_eval/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :group
  belongs_to :project
  belongs_to :student

  has_many :scores, dependent: :delete_all
  accepts_nested_attributes_for :scores
end

peer_eval/app/models/score.rb
class Score < ApplicationRecord
  belongs_to :author, class_name: 'Student'
  belongs_to :recipient, class_name: 'Student'
  belongs_to :review, optional: true

  validates :rating, presence: true
end

peer_eval/app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :memberships, dependent: :destroy
  has_many :groups, through: :memberships
  has_many :authored_scores, class_name: "Score", foreign_key: "author_id"
  has_many :received_scores, class_name: "Score", foreign_key: "recipient_id"
  has_many :scores
  has_many :reviews
  has_many :grades
  validates :fname, :lname, :email, presence: true
  validates :groups, absence: { message: 'cannot have admins as members' }, if: :isAdmin?
  validates_uniqueness_of :email
end

peer_eval/app/helpers/application_helper.rb
module ApplicationHelper
end

peer_eval/app/helpers/assignments_helper.rb
module AssignmentsHelper
end

peer_eval/app/helpers/grades_helper.rb
module GradesHelper
end

peer_eval/app/helpers/groups_helper.rb
module GroupsHelper
end

peer_eval/app/helpers/memberships_helper.rb
module MembershipsHelper
end

peer_eval/app/helpers/projects_helper.rb
module ProjectsHelper
end

peer_eval/app/helpers/reviews_helper.rb
module ReviewsHelper

end

peer_eval/app/helpers/scores_helper.rb
module ScoresHelper
  def average_score(project, user)
    sum = 0.0
    count = 0.0
    scores = Score.where(recipient_id: user)
    puts scores.length
    scores.each do |score|
      if (Review.find_by(id: score.review_id).project_id == project)
        sum += score.rating
        count += 1
      end
    end
    return sum/count
  end

  def setup_grade(student, project)
    grade = Grade.find_by(student_id: student.id, project_id: project.id)
    if grade == nil
      Grade.new(params[:grade])
    else
      grade
    end
  end
end

peer_eval/app/helpers/students_helper.rb
module StudentsHelper
end

peer_eval/app/views/layouts/_adminHeader.html.erb
<table>
	<tr>
		<th><%= link_to "Students", "/Students" %></th>
		<th><%= link_to "Groups", "/Groups" %></th>
		<th><%= link_to "Projects", "/Projects" %></th>
	</tr>
</table>

peer_eval/app/views/layouts/_admin_header.erb
<table>
	<tr>

	</tr>
</table>

peer_eval/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Peer Evaluation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <table>
      <tr style="padding-bottom:15px" class = "header">
        <% if current_student.try(:isAdmin?) %>
        <th class="th1"><%= link_to "Students", "/students" %></th>
        <th class="th2"><%= link_to "Groups", "/groups" %></th>
        <th class="th3"><%= link_to "Projects", "/projects" %></th>
        <th class="th4"><%= link_to "Scores", "/scores" %></th>
        <%#else%>
        <%end%>
      </tr>
    </table>
    <p class="navbar">
      <% if student_signed_in? %>
        Logged in as <strong><%= current_student.email %></strong>.
        <%= link_to 'Edit profile', edit_student_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_student_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_student_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_student_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
    
    <%# if notice %>
<!--    <p class="alert alert-success"><%#= notice %></p>-->
    <%# if notice %>
<!--      <p class="alert alert-success"><%#= notice %></p>-->
    <%# end %>
    <%# if alert %>
<!--      <p class="alert alert-danger"><%#= alert %></p>-->
    <%# end %>
  <%# end %>
  <%# if alert %>
<!--    <p class="alert alert-danger"><%#= alert %></p>-->
  <%# end %>
    <%= yield %>
  </body>
</html>