peer_eval/config/routes.rb
Rails.application.routes.draw do
	get 'reviews/:id', to: 'peer_evaluations#index'
 	devise_for :students, path: 'u'
	resources :students
	resources :groups
	resources :projects
	resources :assignments
	resources :memberships
	resources :scores
	resources :reviews
	resources :peer_evaluations
  resources :grades

	root to: 'students#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

peer_eval/app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :students, through: :memberships
  has_many :assignments, dependent: :destroy
  has_many :projects, through: :assignments
  has_many :reviews
  validates :name, presence: true, uniqueness: true
end

peer_eval/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
    unless current_student.try(:isAdmin?)
      render(:file => File.join(Rails.root, 'public/403'), :formats => [:html], :status => 403, :layout => false)
    end
  end

  # GET /groups/1 or /groups/1.json
  def show
    @group = Group.find(params[:id])
    @students = @group.students
    @projects = @group.projects
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    if params[:group][:student_ids] 
      params[:group][:student_ids].each { |student_id| 
        @group.students << Student.find(student_id)
      }
    end

    if params[:group][:project_ids] 
      params[:group][:project_ids].each { |project_id| 
        @group.projects << Project.find(project_id)
      }
    end

    respond_to do |format|
      if @group.save
        @groups = Group.all
        format.html { render action: "index", notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    @group.students = []
    @group.projects = []
    if params[:group][:student_ids] 
      params[:group][:student_ids].each { |student_id| 
        @group.students << Student.find(student_id)
      }
    end

    if params[:group][:project_ids] 
      params[:group][:project_ids].each { |project_id| 
        @group.projects << Project.find(project_id)
      }
    end
    respond_to do |format|
      if @group.update(group_params)
        @groups = Group.all
        format.html { render action: "index", notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name)
    end
end

peer_eval/app/helpers/groups_helper.rb
module GroupsHelper
end

peer_eval/app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation" class = "error">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class = "checks">
    <% if Student.all.length > 0 %>
      <h3 id = "title">Group Members</h3>
      <% Student.all.select {|student| !student.isAdmin }.sort_by(&:lname).each do |student| %>
        <%= check_box_tag "group[student_ids][]", student.id, @group.students.include?(student) %>
        <%= student.fname %> <%= student.lname %> <%= student.email %>
        <br>
      <% end %>
    <% end %>
  </div>

  <div class = "checks">
    <% if Project.all.length > 0 %>
      <h3 id = "title">Assignments</h3>
      <% Project.all.sort_by(&:title).each do |project| %>
        <%= check_box_tag "group[project_ids][]", project.id, @group.projects.include?(project) %>
        <%= project.title %>
        <br />
      <% end %>
      <br>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

peer_eval/app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

peer_eval/app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Groups</h1>

<table class="infoTable2">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"> </th>
    </tr>
  </thead>

  <tbody>
    <% @groups.sort_by(&:name).each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><button class="infoButton2"><%= link_to 'Details', group %></button></td>
        <td><button class="infoButton2"><%= link_to 'Edit', edit_group_path(group) %></button></td>
        <td><button class="infoButton2"><%= link_to 'Delete', group, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button class="addButton2"><%= link_to 'New Group', new_group_path %></button>

peer_eval/app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

peer_eval/app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @group.name %></h2>

<% if @students.length > 0 %>
	<h3>Group Member(s)</h3>	
	<% @students.each do |student| %>
	  <div class = "checks">
	    <li><%= student.fname %> <%= student.lname %> <%= student.email %> <br></li>
	  </div>
	<% end %>
	<br>
<% else %>
  <h3>This Group Currently has No Members</h3>
<% end %>

<% if @projects.length > 0 %>
	<h3>Project(s) Assigned</h3>
	<% @projects.each do |project| %>
	  <div class = "checks">
	    <li><%= project.title %> <br></li>
	  </div>
	<% end %>
	<br>
<% else %>
  	<h3>This Group is not Currently Assigned to Any Projects</h3>
<% end %>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>